const questions = [
      {
      q: "What does the Law of Conservation of Charge state?",
      options: [
        "Charge can be created or destroyed in any process",
        "Total charge remains constant in an isolated system",
        "Electrons cannot move in conductors",
        "Charge flows only in closed circuits"
      ],
      answer: 1
    },
    {
      q: "Which of the following devices demonstrates Joule heating?",
      options: [
        "Transformer",
        "Electric Kettle",
        "LED Bulb",
        "Microwave Oven"
      ],
      answer: 1
    },
    {
      q: "What is the cause of heat production in conductors?",
      options: [
        "Electromagnetic radiation",
        "Ions in the conductor",
        "Collisions of electrons with atoms",
        "Movement of protons"
      ],
      answer: 2
    },
    {
      q: "Joule's law relates heat produced to:",
      options: [
        "Current, resistance, and time",
        "Voltage and current only",
        "Capacitance and voltage",
        "Charge and temperature"
      ],
      answer: 0
    },
    {
      q: "Which of the following best represents conservation of charge?",
      options: [
        "Charge disappears in a capacitor",
        "Charge in equals charge out",
        "Charge changes sign",
        "Positive charge dominates negative"
      ],
      answer: 1
    },
    {
      q: "Joule effect is undesirable in:",
      options: [
        "Electric heater",
        "Electric bulb",
        "Power transmission lines",
        "Water heater"
      ],
      answer: 2
    },
    {
      q: "Which unit is used to express the heat generated by Joule heating?",
      options: [
        "Ampere",
        "Ohm",
        "Joule",
        "Watt"
      ],
      answer: 2
    },
    {
      q: "In electrostatics, Joule heating occurs due to:",
      options: [
        "Capacitor discharge",
        "Potential drop",
        "Steady current flow",
        "Displacement current"
      ],
      answer: 2
    },
    {
      q: "Which experiment supports conservation of charge?",
      options: [
        "Millikan’s oil drop",
        "Photoelectric effect",
        "Rutherford’s scattering",
        "Young’s double slit"
      ],
      answer: 0
    },
    {
      q: "What is the immediate effect of a current spike in a resistor?",
      options: [
        "Increase in mass",
        "Charge neutralization",
        "Heat generation",
        "Voltage drop to zero"
      ],
      answer: 2
    },
  {
      q: "What defines an electric dipole?",
      options: [
        "Two charges of equal magnitude",
        "Two opposite charges separated by a distance",
        "A single charge in a field",
        "A loop of current",
      ],
      answer: 1
    },
    {
      q: "Dipole moment is a:",
      options: [
        "Scalar",
        "Pseudo scalar",
        "Vector",
        "Tensor"
      ],
      answer: 2
    },
    {
      q: "Direction of dipole moment vector is from:",
      options: [
        "Positive to negative",
        "Negative to positive",
        "Center to charge",
        "Charge to center"
      ],
      answer: 1
    },
    {
      q: "Torque on a dipole in uniform electric field depends on:",
      options: [
        "Dipole length only",
        "Charge only",
        "Angle with field",
        "Area enclosed"
      ],
      answer: 2
    },
    {
      q: "Dipole potential is highest: ",
      options: [
        "At equator",
        "On the axis",
        "At midpoint",
        "Very far away"
      ],
      answer: 1
    },
    {
      q: "Torque on a dipole is zero when:",
      options: [
        "Dipole is at 45°",
        "Dipole is perpendicular to E",
        "Dipole is aligned with E",
        "Dipole is at origin"
      ],
      answer: 2
    },
    {
      q: "Dipole field decreases with distance as:",
      options: [
        "1/r",
        "1/r^2",
        "1/r^3",
        "1/r^4"
      ],
      answer: 2
    },
    {
      q: "The unit of dipole moment is:",
      options: [
        "Coulomb",
        "Volt",
        "C·m",
        "N·m"
      ],
      answer: 2
    },
    {
      q: "Dipole placed in a field tends to:",
      options: [
        "Move to infinity",
        "Align with the field",
        "Gain charge",
        "Oscillate forever"
      ],
      answer: 1
    },
    {
      q: "Potential energy is minimum when dipole is:",
      options: [
        "At 90°",
        "At 45°",
        "Aligned with field",
        "Opposite to field"
      ],
      answer: 2
    },
    {
      q: "What is an electric quadrupole?",
      options: [
        "Two equal and opposite charges",
        "Arrangement of four equal charges",
        "Two dipoles placed close together",
        "A rotating magnetic field"
      ],
      answer: 2
    },
    {
      q: "Electric multipoles are used in:",
      options: [
        "Radar design",
        "Solar panels",
        "Vacuum tubes",
        "Transistors"
      ],
      answer: 0
    },
    {
      q: "Which of these represents a higher-order multipole?",
      options: [
        "Monopole",
        "Dipole",
        "Quadrupole",
        "Single charge"
      ],
      answer: 2
    },
    {
      q: "Electric dipoles are best for modeling:",
      options: [
        "DC motor field",
        "Point charge",
        "Molecular polarity",
        "Current direction"
      ],
      answer: 2
    },
    {
      q: "A quadrupole has net charge equal to:",
      options: [
        "Positive",
        "Negative",
        "Zero",
        "Infinite"
      ],
      answer: 2
    },
    {
      q: "Dipole radiation patterns are used in:",
      options: [
        "Audio circuits",
        "Antennas",
        "Battery design",
        "Thermistors"
      ],
      answer: 1
    },
    {
      q: "Multipole expansion is important in:",
      options: [
        "Capacitor discharge",
        "Far-field analysis",
        "Series circuits",
        "Parallel resistor calculation"
      ],
      answer: 1
    },
    {
      q: "Electric quadrupoles appear in:",
      options: [
        "X-ray devices",
        "Atomic nuclei modeling",
        "Laser mirrors",
        "Wiring insulation"
      ],
      answer: 1
    },
    {
      q: "Dipole is a special case of:",
      options: [
        "Monopole",
        "Multipole",
        "Electrolyte",
        "Ohmic conductor"
      ],
      answer: 1
    },
    {
      q: "Multipoles describe field patterns in:",
      options: [
        "Point systems",
        "Complex charge distributions",
        "Homogeneous metals",
        "Insulators"
      ],
      answer: 1
    },
    {
      q: "Electric potential energy increases when:",
      options: [
        "Like charges are moved apart",
        "Opposite charges are brought closer",
        "Like charges are brought together",
        "No force acts"
      ],
      answer: 2
    },
    {
      q: "Which has highest potential energy?",
      options: [
        "Two electrons far apart",
        "Two protons together",
        "Proton and electron far apart",
        "Proton and electron together"
      ],
      answer: 1
    },
    {
      q: "Potential energy of continuous charge depends on:",
      options: [
        "Charge density only",
        "Volume and potential",
        "Position and shape",
        "Temperature"
      ],
      answer: 1
    },
    {
      q: "Electric potential is scalar because:",
      options: [
        "It depends on direction",
        "It is derived from force",
        "It has no direction",
        "It adds vectorially"
      ],
      answer: 2
    },
    {
      q: "Work done in bringing a charge to a point defines:",
      options: [
        "Current",
        "Electric flux",
        "Electric field",
        "Electric potential"
      ],
      answer: 3
    },
    {
      q: "Potential energy is zero for:",
      options: [
        "Point charge at infinity",
        "Line charge",
        "Equal charges close together",
        "Negative charge near positive"
      ],
      answer: 0
    },
    {
      q: "Which unit represents potential energy?",
      options: [
        "Volt",
        "Coulomb",
        "Joule",
        "Ampere"
      ],
      answer: 2
    },
    {
      q: "Energy stored in electrostatic field is due to:",
      options: [
        "Mass of particles",
        "Vacuum interaction",
        "Charge configuration",
        "Electron rotation"
      ],
      answer: 2
    },
    {
      q: "Line charge energy depends on:",
      options: [
        "Area",
        "Length and density",
        "Capacitance",
        "Resistance"
      ],
      answer: 1
    },
    {
      q: "Potential difference between two points implies:",
      options: [
        "Current flow",
        "Resistance",
        "Energy change",
        "Capacitance"
      ],
      answer: 2
    },
   {
      q: "What happens to capacitance if the plate area increases?",
      options: ["Increases", "Decreases", "Remains same", "Becomes zero"],
      answer: 0
    },
    {
      q: "What happens to capacitance if the distance between plates increases?",
      options: ["Increases", "Decreases", "Remains same", "Doubles"],
      answer: 1
    },
    {
      q: "Capacitance depends on:",
      options: ["Resistance", "Charge only", "Area and distance", "Inductance"],
      answer: 2
    },
    {
      q: "Dielectric in a capacitor:",
      options: ["Reduces capacitance", "Increases capacitance", "Has no effect", "Destroys plates"],
      answer: 1
    },
    {
      q: "Unit of capacitance is:",
      options: ["Coulomb", "Ohm", "Farad", "Volt"],
      answer: 2
    },
    {
      q: "Which material improves capacitor efficiency?",
      options: ["Air", "Copper", "Glass", "Iron"],
      answer: 2
    },
    {
      q: "Parallel plate capacitor stores energy in the:",
      options: ["Conductors", "Dielectric", "Magnetic field", "Electric field"],
      answer: 3
    },
    {
      q: "Which of the following increases with dielectric?",
      options: ["Resistance", "Charge", "Capacitance", "Voltage"],
      answer: 2
    },
    {
      q: "What is the effect of inserting a dielectric fully?",
      options: ["Voltage increases", "Voltage drops to zero", "Capacitance increases", "Electric field disappears"],
      answer: 2
    },
    {
      q: "Capacitor is mainly used for:",
      options: ["Generating heat", "Energy storage", "Induction", "Creating sound"],
      answer: 1
    },
   {
      q: "Electric field inside a conductor is:",
      options: ["Maximum", "Zero", "Equal to surface field", "Infinite"],
      answer: 1
    },
    {
      q: "Charges on a conductor reside:",
      options: ["Inside volume", "Evenly throughout", "On the surface", "In the air gap"],
      answer: 2
    },
    {
      q: "Boundary condition at conductor surface involves:",
      options: ["Magnetic force", "Surface charge density", "Permeability", "Displacement current"],
      answer: 1
    },
    {
      q: "Conductor in electrostatics has:",
      options: ["Free moving charges", "No charges", "Only negative charge", "Superconductivity"],
      answer: 0
    },
    {
      q: "Electric field just outside a conductor is:",
      options: ["Parallel to surface", "Tangential", "Perpendicular", "Zero"],
      answer: 2
    },
    {
      q: "Inside a conducting shell, electric field is:",
      options: ["Uniform", "Zero", "Infinite", "Oscillating"],
      answer: 1
    },
    {
      q: "Conductor shields from:",
      options: ["Sound waves", "Magnetic field", "Electric field", "Heat"],
      answer: 2
    },
    {
      q: "Which law governs force between charges on conductors?",
      options: ["Faraday’s law", "Coulomb’s law", "Ampere’s law", "Gauss’s law"],
      answer: 1
    },
    {
      q: "Electrostatic shielding is used in:",
      options: ["Heating systems", "Microwave ovens", "Faraday cages", "Capacitor banks"],
      answer: 2
    },
    {
      q: "Which field exists outside a charged conductor?",
      options: ["Tangential field", "Zero field", "Radial electric field", "Uniform field"],
      answer: 2
    },
]
